-- Expand popular freshwater fish (incl. blood parrot and common cichlids / community staples).
-- Safe to re-run: skips existing slugs.

insert into public.species_catalog (
  slug, common_name, scientific_name, kind, min_tank_gallons, adult_length_inches,
  bioload_factor, invert_points, temperament, reef_safe, diet, lighting, flow,
  aggression_tags, temp_min, temp_max, salinity_min, salinity_max, ph_min, ph_max,
  alk_min, alk_max, ca_min, ca_max, no3_min, no3_max, po4_min, po4_max, notes, water_type
) values
-- New World / Central American cichlids
('blood-parrot-cichlid','Blood parrot cichlid','Amphilophus citrinellus x Vieja melanurus','fish',40,8.0,1.8,0,'semi_aggressive','yes','omnivore',null,null,'{territorial}',76,84,null,null,6.5,7.8,4,12,null,null,0,40,0,1,'Hybrid cichlid (man-made). Rounded body, often orange/red; may have bite/feeding quirks. Soften tankmates carefully.','freshwater'),
('flowerhorn-cichlid','Flowerhorn cichlid','Amphilophus hybrid','fish',75,12.0,2.2,0,'aggressive','yes','omnivore',null,null,'{territorial,eats_inverts}',78,86,null,null,6.5,8.0,4,15,null,null,0,40,0,1,'Hybrid show cichlid with nuchal hump. Best alone or with carefully chosen tankmates.','freshwater'),
('firemouth-cichlid','Firemouth cichlid','Thorichthys meeki','fish',40,6.0,1.3,0,'semi_aggressive','yes','omnivore',null,null,'{territorial}',72,82,null,null,6.5,7.8,4,12,null,null,0,40,0,1,'Flashes a red throat when displaying. Digs; keep hardy plants or hardscape only.','freshwater'),
('jewel-cichlid','Jewel cichlid','Hemichromis bimaculatus','fish',40,5.0,1.2,0,'aggressive','yes','omnivore',null,null,'{territorial}',72,82,null,null,6.5,7.8,4,12,null,null,0,40,0,1,'Brilliant red when spawning. Very territorial — species tank or tough neighbors only.','freshwater'),
('jack-dempsey','Jack Dempsey','Rocio octofasciata','fish',55,10.0,1.8,0,'aggressive','yes','carnivore',null,null,'{territorial,eats_inverts}',72,86,null,null,6.5,8.0,4,15,null,null,0,40,0,1,'Classic Central American bully. Needs room and sturdy décor.','freshwater'),
('green-terror','Green terror','Andinoacara rivulatus','fish',55,12.0,2.0,0,'aggressive','yes','carnivore',null,null,'{territorial,eats_inverts}',70,82,null,null,6.5,8.0,4,15,null,null,0,40,0,1,'Large beautiful CA cichlid. Pair carefully; digs heavily.','freshwater'),
('texas-cichlid','Texas cichlid','Herichthys cyanoguttatus','fish',75,12.0,2.0,0,'aggressive','yes','omnivore',null,null,'{territorial,eats_inverts}',68,82,null,null,6.5,8.0,4,15,null,null,0,40,0,1,'Hardy North American cichlid. Big and territorial as an adult.','freshwater'),
('red-devil-cichlid','Red devil cichlid','Amphilophus labiatus','fish',75,14.0,2.3,0,'aggressive','yes','carnivore',null,null,'{territorial,eats_inverts}',72,84,null,null,6.5,8.0,4,15,null,null,0,40,0,1,'Often kept alone. Rearranges rockwork and eats small fish.','freshwater'),
('midas-cichlid','Midas cichlid','Amphilophus citrinellus','fish',75,14.0,2.3,0,'aggressive','yes','omnivore',null,null,'{territorial,eats_inverts}',74,84,null,null,6.5,8.0,4,15,null,null,0,40,0,1,'Parent species often used in parrot/flowerhorn lines. Large and bold.','freshwater'),
('severum','Severum','Heros efasciatus','fish',55,8.0,1.5,0,'semi_aggressive','yes','omnivore',null,null,'{territorial}',74,82,null,null,5.5,7.2,2,10,null,null,0,30,0,0.8,'Gold and green varieties common. Soft acidic water preferred.','freshwater'),
('uara-cichlid','Uaru / triangle cichlid','Uaru amphiacanthoides','fish',75,10.0,1.8,0,'peaceful','yes','omnivore',null,null,'{}',78,84,null,null,5.5,7.0,2,8,null,null,0,30,0,0.5,'Sensitive to water quality. Soft warm water Amazonian.','freshwater'),
('festivum','Festivum / flag cichlid','Mesonauta festivus','fish',40,6.0,1.2,0,'peaceful','yes','omnivore',null,null,'{}',75,82,null,null,5.5,7.5,2,10,null,null,0,30,0,0.8,'Peaceful mid-sized SA cichlid. Good angelfish companion.','freshwater'),
('keyhole-cichlid','Keyhole cichlid','Cleithracara maronii','fish',30,4.0,0.9,0,'peaceful','yes','omnivore',null,null,'{}',72,82,null,null,5.5,7.5,2,10,null,null,0,30,0,0.8,'Shy dwarf-ish cichlid with a dark keyhole blotch.','freshwater'),
('blue-acara','Blue acara','Andinoacara pulcher','fish',40,6.0,1.3,0,'semi_aggressive','yes','omnivore',null,null,'{territorial}',72,82,null,null,6.5,8.0,4,12,null,null,0,40,0,1,'Hardy community cichlid when given space. Digs.','freshwater'),
('kribensis','Kribensis','Pelvicachromis pulcher','fish',20,4.0,0.9,0,'semi_aggressive','yes','omnivore',null,null,'{territorial,caves}',72,82,null,null,5.5,7.5,2,10,null,null,0,30,0,0.8,'West African dwarf. Pair with caves; colorful when spawning.','freshwater'),
('rainbow-cichlid','Rainbow cichlid','Herotilapia multispinosa','fish',40,5.0,1.1,0,'semi_aggressive','yes','omnivore',null,null,'{territorial}',72,82,null,null,6.5,8.0,4,12,null,null,0,40,0,1,'Yellow-orange CA cichlid. Digs and claims territory when breeding.','freshwater'),
('salvini-cichlid','Salvini cichlid','Trichromis salvini','fish',55,6.0,1.3,0,'aggressive','yes','carnivore',null,null,'{territorial}',72,82,null,null,6.5,8.0,4,12,null,null,0,40,0,1,'Striking tiger-striped CA cichlid. Not for peaceful community tanks.','freshwater'),
('chocolate-cichlid','Chocolate cichlid','Hypselecara temporalis','fish',55,10.0,1.7,0,'semi_aggressive','yes','omnivore',null,null,'{territorial}',76,84,null,null,5.5,7.5,2,10,null,null,0,30,0,0.8,'Large softwater SA cichlid. Warm and clean water.','freshwater'),
('eartheater-geophagus','Geophagus / eartheater','Geophagus spp.','fish',55,7.0,1.4,0,'peaceful','yes','omnivore',null,null,'{needs_sand}',76,84,null,null,5.5,7.5,2,10,null,null,0,30,0,0.5,'Sand-sifting South American cichlid. Needs fine sand and groups.','freshwater'),
('pike-cichlid','Pike cichlid','Crenicichla spp.','fish',55,10.0,1.6,0,'aggressive','yes','carnivore',null,null,'{territorial,eats_inverts}',72,82,null,null,5.5,7.5,2,10,null,null,0,30,0,0.8,'Ambush predator. Size varies widely by species — research the ID.','freshwater'),
('flag-cichlid-laetacara','Dwarf flag cichlid','Laetacara curviceps','fish',20,3.0,0.7,0,'peaceful','yes','omnivore',null,null,'{territorial}',74,82,null,null,5.5,7.2,2,8,null,null,0,30,0,0.5,'Small peaceful SA dwarf. Soft acidic water.','freshwater'),
('ramirezi-electric-blue','Electric blue ram','Mikrogeophagus ramirezi','fish',20,2.5,0.7,0,'peaceful','yes','omnivore',null,null,'{delicate}',78,86,null,null,5.5,7.0,1,6,null,null,0,20,0,0.3,'Blue morph of German blue ram. Warm soft water; sensitive.','freshwater'),

-- African cichlids (beyond peacock / yellow lab / frontosa)
('kenyi-cichlid','Kenyi cichlid','Maylandia lombardoi','fish',55,5.0,1.2,0,'aggressive','yes','omnivore',null,null,'{territorial}',74,82,null,null,7.8,8.6,10,18,null,null,0,40,0,1,'Malawi mbuna. Males turn yellow; females/juveniles blue.','freshwater'),
('demasoni-cichlid','Demasoni cichlid','Pseudotropheus demasoni','fish',55,3.5,1.0,0,'aggressive','yes','omnivore',null,null,'{territorial}',74,82,null,null,7.8,8.6,10,18,null,null,0,40,0,1,'Tiny but fiercely territorial mbuna. Overstock carefully in big tanks.','freshwater'),
('acei-cichlid','Acei cichlid','Pseudotropheus acei','fish',55,5.0,1.1,0,'semi_aggressive','yes','omnivore',null,null,'{territorial}',74,82,null,null,7.8,8.6,10,18,null,null,0,40,0,1,'Yellow-tail Malawi. Among the milder mbuna.','freshwater'),
('cobalt-zebra','Cobalt zebra cichlid','Maylandia callainos','fish',55,5.0,1.2,0,'aggressive','yes','omnivore',null,null,'{territorial}',74,82,null,null,7.8,8.6,10,18,null,null,0,40,0,1,'Solid blue Malawi mbuna. Needs rockwork and hard alkaline water.','freshwater'),
('auratus-cichlid','Auratus cichlid','Melanochromis auratus','fish',55,4.5,1.1,0,'aggressive','yes','omnivore',null,null,'{territorial}',74,82,null,null,7.8,8.6,10,18,null,null,0,40,0,1,'Gold-and-black Malawi. Females/juveniles look different from males.','freshwater'),
('tropheus-moorii','Tropheus moorii','Tropheus moorii','fish',75,5.0,1.2,0,'aggressive','yes','herbivore',null,null,'{territorial,delicate}',76,82,null,null,7.8,9.0,10,18,null,null,0,30,0,0.5,'Tanganyika algae browser. Keep in groups; sensitive guts — veggie diet.','freshwater'),
('compressiceps','Compressiceps','Altolamprologus compressiceps','fish',40,5.0,1.0,0,'semi_aggressive','yes','carnivore',null,null,'{territorial,caves,eats_inverts}',74,82,null,null,7.8,9.0,10,18,null,null,0,40,0,1,'Tanganyika shell/rock dweller. May eat small shrimp.','freshwater'),
('calvus','Calvus','Altolamprologus calvus','fish',40,5.0,1.0,0,'semi_aggressive','yes','carnivore',null,null,'{territorial,caves}',74,82,null,null,7.8,9.0,10,18,null,null,0,40,0,1,'Pearlescent Tanganyika cichlid. Cave spawner.','freshwater'),
('frontosa-blue','Blue Zaire frontosa','Cyphotilapia frontosa','fish',125,14.0,2.0,0,'semi_aggressive','yes','carnivore',null,null,'{territorial}',74,80,null,null,7.8,9.0,10,18,null,null,0,40,0,1,'Large Tanganyika show fish. Needs a big tank and cooler temps.','freshwater'),
('orange-chromide','Orange chromide','Etroplus maculatus','fish',30,3.5,0.9,0,'peaceful','yes','omnivore',null,null,'{}',72,82,null,null,7.0,8.5,6,15,null,null,0,40,0,1,'Brackish-tolerant Indian cichlid. Often kept in hard freshwater.','freshwater'),

-- Livebearers & popular community
('sailfin-molly','Sailfin molly','Poecilia latipinna','fish',30,5.0,1.0,0,'peaceful','yes','omnivore',null,null,'{}',72,82,null,null,7.0,8.5,8,18,null,null,0,40,0,1,'Larger molly with a tall dorsal. Hard alkaline water; some prefer light brackish.','freshwater'),
('balloon-molly','Balloon molly','Poecilia sphenops','fish',20,3.0,0.8,0,'peaceful','yes','omnivore',null,null,'{delicate}',72,82,null,null,7.0,8.5,8,18,null,null,0,40,0,1,'Deformity morph — watch buoyancy and spine issues. Hard water.','freshwater'),
('black-molly','Black molly','Poecilia sphenops','fish',20,3.0,0.8,0,'peaceful','yes','omnivore',null,null,'{}',72,82,null,null,7.0,8.5,8,18,null,null,0,40,0,1,'Classic black livebearer. Prefers hard water and some salt if desired.','freshwater'),
('lyretail-swordtail','Lyretail swordtail','Xiphophorus hellerii','fish',30,4.5,0.9,0,'peaceful','yes','omnivore',null,null,'{}',70,82,null,null,7.0,8.2,6,15,null,null,0,40,0,1,'Fancy swordtail morph. Keep one male per several females.','freshwater'),
('wagtail-platy','Wagtail platy','Xiphophorus maculatus','fish',15,2.5,0.6,0,'peaceful','yes','omnivore',null,null,'{}',70,82,null,null,7.0,8.2,6,15,null,null,0,40,0,1,'High-contrast platy morph. Easy community livebearer.','freshwater'),
('mosquito-fish','Mosquitofish','Gambusia affinis','fish',10,2.5,0.5,0,'semi_aggressive','yes','carnivore',null,null,'{territorial}',50,86,null,null,6.5,8.5,4,15,null,null,0,40,0,1,'Hardy outdoor/pond livebearer. Can nip slower fish.','freshwater'),

-- Barbs, danios, rasboras
('rosy-barb','Rosy barb','Pethia conchonius','fish',30,4.0,0.9,0,'peaceful','yes','omnivore',null,null,'{}',64,78,null,null,6.0,8.0,4,12,null,null,0,40,0,1,'Cooler-tolerant barb. Keep a school of 6+.','freshwater'),
('odessa-barb','Odessa barb','Pethia padamya','fish',30,3.0,0.8,0,'peaceful','yes','omnivore',null,null,'{}',72,79,null,null,6.0,8.0,4,12,null,null,0,40,0,1,'Males flash a red lateral stripe. Schooling barb.','freshwater'),
('gold-barb','Gold barb','Barbodes semifasciolatus','fish',30,3.0,0.8,0,'peaceful','yes','omnivore',null,null,'{}',64,78,null,null,6.0,8.0,4,12,null,null,0,40,0,1,'Peaceful golden barb. Good community schooler.','freshwater'),
('denison-barb','Denison barb / roseline shark','Sahyadria denisonii','fish',55,6.0,1.3,0,'peaceful','yes','omnivore',null,null,'{}',72,79,null,null,6.5,7.8,4,12,null,null,0,40,0,1,'Active streamlined barb. Needs swimming room and a group.','freshwater'),
('clown-barb','Clown barb','Barbodes everetti','fish',40,5.0,1.1,0,'peaceful','yes','omnivore',null,null,'{}',72,82,null,null,6.0,7.5,3,10,null,null,0,40,0,1,'Orange-spotted barb. Keep in a school.','freshwater'),
('checkerboard-barb','Checkerboard barb','Oliotius oligolepis','fish',20,2.0,0.5,0,'peaceful','yes','omnivore',null,null,'{}',72,79,null,null,5.5,7.5,2,10,null,null,0,30,0,0.8,'Small peaceful barb for planted tanks.','freshwater'),
('pearl-danio','Pearl danio','Danio albolineatus','fish',20,2.5,0.5,0,'peaceful','yes','omnivore',null,null,'{}',68,78,null,null,6.0,8.0,4,12,null,null,0,40,0,1,'Active surface schooler. Keep a group.','freshwater'),
('giant-danio','Giant danio','Devario aequipinnatus','fish',40,4.0,0.9,0,'peaceful','yes','omnivore',null,null,'{}',72,79,null,null,6.0,8.0,4,12,null,null,0,40,0,1,'Fast midwater fish. Needs swimming space.','freshwater'),
('leopard-danio','Leopard danio','Danio rerio','fish',15,2.0,0.4,0,'peaceful','yes','omnivore',null,null,'{}',64,78,null,null,6.0,8.0,4,12,null,null,0,40,0,1,'Spotted danio morph (same species as zebra). School of 6+.','freshwater'),
('lambchop-rasbora','Lambchop rasbora','Trigonostigma espei','fish',15,1.5,0.4,0,'peaceful','yes','omnivore',null,null,'{}',72,82,null,null,5.5,7.2,2,8,null,null,0,30,0,0.5,'Small peaceful rasbora. Soft water preferred.','freshwater'),
('scissortail-rasbora','Scissortail rasbora','Rasbora trilineata','fish',30,4.0,0.8,0,'peaceful','yes','omnivore',null,null,'{}',72,79,null,null,6.0,7.5,3,10,null,null,0,40,0,1,'Active schooling rasbora with forked tail markings.','freshwater'),

-- Tetras & characins
('black-phantom-tetra','Black phantom tetra','Hyphessobrycon megalopterus','fish',15,1.8,0.4,0,'peaceful','yes','omnivore',null,null,'{}',72,82,null,null,5.5,7.5,2,10,null,null,0,30,0,0.5,'Peaceful schooler. Males have larger dorsal fins.','freshwater'),
('red-phantom-tetra','Red phantom tetra','Hyphessobrycon sweglesi','fish',15,1.6,0.4,0,'peaceful','yes','omnivore',null,null,'{}',72,82,null,null,5.5,7.5,2,10,null,null,0,30,0,0.5,'Warm softwater tetra. Keep a group.','freshwater'),
('diamond-tetra','Diamond tetra','Moenkhausia pittieri','fish',30,2.5,0.6,0,'peaceful','yes','omnivore',null,null,'{}',72,82,null,null,5.5,7.5,2,10,null,null,0,30,0,0.5,'Sparkling scales. Soft acidic water shines their color.','freshwater'),
('emperor-tetra','Emperor tetra','Nematobrycon palmeri','fish',20,2.0,0.5,0,'peaceful','yes','omnivore',null,null,'{}',72,82,null,null,5.0,7.5,2,8,null,null,0,30,0,0.5,'Elegant tetra with a dark lateral line. Soft water.','freshwater'),
('penguin-tetra','Penguin tetra','Thayeria boehlkei','fish',20,2.5,0.5,0,'peaceful','yes','omnivore',null,null,'{}',72,82,null,null,5.5,7.8,2,10,null,null,0,40,0,1,'Swims at a head-down angle. Peaceful schooler.','freshwater'),
('silvertip-tetra','Silvertip tetra','Hasemania nana','fish',15,1.5,0.4,0,'peaceful','yes','omnivore',null,null,'{}',72,82,null,null,5.5,7.8,2,10,null,null,0,40,0,1,'White-tipped fins. Easy community tetra.','freshwater'),
('colombian-tetra','Colombian tetra','Hyphessobrycon columbianus','fish',30,2.5,0.6,0,'peaceful','yes','omnivore',null,null,'{}',72,82,null,null,6.0,7.8,3,12,null,null,0,40,0,1,'Blue-and-red body. Active schooler.','freshwater'),
('bucktooth-tetra','Bucktooth tetra','Exodon paradoxus','fish',55,6.0,1.2,0,'aggressive','yes','carnivore',null,null,'{territorial,eats_inverts}',74,82,null,null,5.5,7.5,2,10,null,null,0,40,0,1,'Scale-eater. Species tank only — not a community fish.','freshwater'),
('mexican-tetra','Blind cave tetra','Astyanax mexicanus','fish',20,3.5,0.7,0,'peaceful','yes','omnivore',null,null,'{}',64,78,null,null,6.5,8.0,4,15,null,null,0,40,0,1,'Eyeless cave form. Hardier than it looks; keep a group.','freshwater'),
('bloodfin-tetra','Bloodfin tetra','Aphyocharax anisitsi','fish',20,2.0,0.5,0,'peaceful','yes','omnivore',null,null,'{}',64,82,null,null,6.0,8.0,4,12,null,null,0,40,0,1,'Red fins, silver body. Cooler-tolerant schooler.','freshwater'),

-- Catfish, loaches, oddballs
('pictus-catfish','Pictus catfish','Pimelodus pictus','fish',55,5.0,1.2,0,'peaceful','yes','carnivore',null,null,'{eats_inverts,jumps}',72,82,null,null,6.0,7.5,2,12,null,null,0,40,0,1,'Active schooling catfish. Eats small shrimp; keep a lid.','freshwater'),
('bumblebee-catfish','Bumblebee catfish','Microglanis iheringi','fish',20,3.0,0.7,0,'peaceful','yes','carnivore',null,null,'{caves}',72,82,null,null,6.0,7.5,2,10,null,null,0,40,0,1,'Nocturnal dwarf cat. Needs caves and meaty foods.','freshwater'),
('iridescent-shark','Iridescent shark','Pangasianodon hypophthalmus','fish',180,24.0,2.5,0,'peaceful','yes','omnivore',null,null,'{jumps}',72,82,null,null,6.5,7.5,4,12,null,null,0,40,0,1,'NOT a shark — huge migratory catfish. Outgrows almost every home tank.','freshwater'),
('bala-shark','Bala shark','Balantiocheilus melanopterus','fish',125,14.0,1.8,0,'peaceful','yes','omnivore',null,null,'{jumps}',72,82,null,null,6.0,8.0,4,12,null,null,0,40,0,1,'Active cyprinid. Needs a very large tank and a group.','freshwater'),
('dojo-loach','Dojo / weather loach','Misgurnus anguillicaudatus','fish',40,8.0,1.2,0,'peaceful','yes','omnivore',null,null,'{needs_sand}',50,75,null,null,6.0,8.0,4,15,null,null,0,40,0,1,'Cooler water loach. Sensitive to barometric swings; soft sand.','freshwater'),
('zebra-loach','Zebra loach','Botia striata','fish',40,3.5,0.8,0,'peaceful','yes','omnivore',null,null,'{caves}',74,82,null,null,6.0,7.5,2,10,null,null,0,40,0,1,'Social loach — keep 5+. Helps with snails.','freshwater'),
('dwarf-chain-loach','Dwarf chain loach','Ambastaia sidthimunki','fish',30,2.5,0.6,0,'peaceful','yes','omnivore',null,null,'{caves}',75,86,null,null,6.0,7.5,2,10,null,null,0,30,0,0.8,'Small social loach. Warm water and a group.','freshwater'),
('clown-pleco','Clown pleco','Panaqolus maccus','fish',30,3.5,0.8,0,'peaceful','yes','herbivore',null,null,'{caves,cleanup}',74,86,null,null,6.0,7.5,2,10,null,null,0,40,0,1,'Wood-eater. Needs bogwood and caves.','freshwater'),
('rubber-lip-pleco','Rubber lip pleco','Chaetostoma spp.','fish',30,4.0,0.9,0,'peaceful','yes','herbivore',null,null,'{cleanup}',68,78,null,null,6.5,7.8,4,12,null,null,0,40,0,1,'Cooler, well-oxygenated water. Film algae grazer.','freshwater'),
('gold-nugget-pleco','Gold nugget pleco','Baryancistrus spp.','fish',55,7.0,1.3,0,'peaceful','yes','omnivore',null,null,'{caves,cleanup}',78,86,null,null,6.0,7.5,2,10,null,null,0,30,0,0.5,'L-number pleco. Warm soft water and protein-rich diet.','freshwater'),
('sailfin-pleco','Sailfin pleco','Pterygoplichthys gibbiceps','fish',75,16.0,2.0,0,'peaceful','yes','omnivore',null,null,'{cleanup}',72,82,null,null,6.5,7.8,4,12,null,null,0,40,0,1,'Gets huge. Heavy waste producer — plan a large tank.','freshwater'),
('chinese-algae-eater','Chinese algae eater','Gyrinocheilus aymonieri','fish',40,8.0,1.2,0,'semi_aggressive','yes','omnivore',null,null,'{territorial}',72,82,null,null,6.0,8.0,4,12,null,null,0,40,0,1,'Often stops eating algae and nips slime as it ages. Prefer SAE instead.','freshwater'),
('elephant-nose','Elephant nose fish','Gnathonemus petersii','fish',55,9.0,1.2,0,'peaceful','yes','carnivore',null,null,'{delicate,needs_sand}',73,82,null,null,6.0,7.5,2,10,null,null,0,30,0,0.5,'Weakly electric. Soft sand, dim light, no aggressive tankmates.','freshwater'),
('african-butterflyfish','African butterflyfish','Pantodon buchholzi','fish',30,5.0,0.9,0,'peaceful','yes','carnivore',null,null,'{jumps,eats_inverts}',75,86,null,null,6.0,7.5,2,10,null,null,0,30,0,0.5,'Surface predator. Tight lid; will eat small fish/shrimp at the top.','freshwater'),
('senegal-bichir','Senegal bichir','Polypterus senegalus','fish',75,14.0,1.8,0,'peaceful','yes','carnivore',null,null,'{eats_inverts,jumps}',75,82,null,null,6.0,8.0,4,15,null,null,0,40,0,1,'Obligate air breather. Escape artist — secure lid.','freshwater'),
('spotted-gar','Spotted gar (juvenile)','Lepisosteus oculatus','fish',180,24.0,2.5,0,'aggressive','yes','carnivore',null,null,'{eats_inverts}',50,75,null,null,6.5,8.0,4,15,null,null,0,40,0,1,'Native gar — huge adult. Only for specialist huge systems.','freshwater'),

-- Gouramis & anabantoids
('sparkling-gourami','Sparkling gourami','Trichopsis pumila','fish',10,1.5,0.3,0,'peaceful','yes','omnivore',null,null,'{}',72,82,null,null,5.5,7.5,2,8,null,null,0,30,0,0.5,'Tiny croaking gourami relative. Nano peaceful fish.','freshwater'),
('croaking-gourami','Croaking gourami','Trichopsis vittata','fish',15,2.5,0.5,0,'peaceful','yes','omnivore',null,null,'{}',72,82,null,null,5.5,7.5,2,10,null,null,0,30,0,0.5,'Makes audible croaks. Peaceful labyrinth fish.','freshwater'),
('chocolate-gourami','Chocolate gourami','Sphaerichthys osphromenoides','fish',20,2.5,0.5,0,'peaceful','yes','omnivore',null,null,'{delicate}',77,86,null,null,4.0,6.5,0,4,null,null,0,20,0,0.3,'Very soft acidic water specialist. Not a beginner fish.','freshwater'),
('snakeskin-gourami','Snakeskin gourami','Trichopodus pectoralis','fish',55,8.0,1.4,0,'peaceful','yes','omnivore',null,null,'{}',72,86,null,null,6.0,8.0,4,15,null,null,0,40,0,1,'Large peaceful gourami. Needs swimming room.','freshwater'),
('thick-lip-gourami','Thick lip gourami','Trichogaster labiosa','fish',20,3.5,0.7,0,'peaceful','yes','omnivore',null,null,'{}',72,82,null,null,6.0,7.5,3,10,null,null,0,40,0,1,'Milder than dwarf gourami hybrids for many tanks.','freshwater'),
('opaline-gourami','Opaline gourami','Trichopodus trichopterus','fish',30,5.0,1.0,0,'semi_aggressive','yes','omnivore',null,null,'{territorial}',72,82,null,null,6.0,8.0,4,12,null,null,0,40,0,1,'Three-spot morph. Can bully slower fish as adults.','freshwater'),
('halfmoon-betta','Halfmoon betta','Betta splendens','fish',5,3.0,0.6,0,'aggressive','yes','carnivore',null,null,'{territorial}',74,86,null,null,6.0,7.5,2,10,null,null,0,40,0,1,'Long-finned show betta. Best alone or with very peaceful tankmates.','freshwater'),
('crowntail-betta','Crowntail betta','Betta splendens','fish',5,3.0,0.6,0,'aggressive','yes','carnivore',null,null,'{territorial}',74,86,null,null,6.0,7.5,2,10,null,null,0,40,0,1,'Spiked finnage morph. Same solitary care as other splendens.','freshwater'),
('plakat-betta','Plakat betta','Betta splendens','fish',5,2.5,0.6,0,'aggressive','yes','carnivore',null,null,'{territorial}',74,86,null,null,6.0,7.5,2,10,null,null,0,40,0,1,'Short-fin fighting fish — often hardier swimmers than halfmoons.','freshwater'),
('betta-imbellis','Peaceful betta / imbellis','Betta imbellis','fish',15,2.5,0.5,0,'peaceful','yes','carnivore',null,null,'{}',74,84,null,null,5.5,7.5,2,8,null,null,0,30,0,0.5,'Wild-type relative; can be kept in pairs/groups with care.','freshwater'),

-- Rainbowfish
('turquoise-rainbowfish','Turquoise rainbowfish','Melanotaenia lacustris','fish',40,5.0,1.0,0,'peaceful','yes','omnivore',null,null,'{}',72,82,null,null,7.0,8.0,6,15,null,null,0,40,0,1,'Lake Kutubu rainbow. Keep a mixed-sex group.','freshwater'),
('threadfin-rainbow','Threadfin rainbowfish','Iriatherina werneri','fish',20,2.0,0.4,0,'peaceful','yes','omnivore',null,null,'{delicate}',74,84,null,null,5.5,7.5,2,8,null,null,0,30,0,0.5,'Delicate nano rainbow. Soft water and gentle tankmates.','freshwater'),
('red-rainbowfish','Red rainbowfish','Glossolepis incisus','fish',40,6.0,1.1,0,'peaceful','yes','omnivore',null,null,'{}',72,82,null,null,7.0,8.0,6,15,null,null,0,40,0,1,'Males turn deep red with age. Active schooler.','freshwater'),
('australian-rainbowfish','Australian rainbowfish','Melanotaenia splendida','fish',40,5.0,1.0,0,'peaceful','yes','omnivore',null,null,'{}',72,82,null,null,6.5,8.0,5,15,null,null,0,40,0,1,'Hardy rainbow. Keep 6+ with plants and open swimming space.','freshwater')
on conflict (slug) do nothing;
